<a href="https://colab.research.google.com/github/Tieh88/Dive-Into-Code/blob/main/Blending.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sprint 8

## Problem 1

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("train.csv")
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [ ]:
X = df[["GrLivArea", "YearBuilt"]]
X.head()

GrLivArea  YearBuilt
0       1710       2003
1       1262       1976
2       1786       2001
3       1717       1915
4       2198       2000

In [ ]:
y = df["SalePrice"]
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3, random_state=0, shuffle=True)
X_train.head()

GrLivArea  YearBuilt
64         2034       1997
682        1291       1996
960         858       1958
1384       1258       1939
1100        438       1920

In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression

In [ ]:
LM= linear_model.LinearRegression(normalize=True)
LM.fit(X_train, y_train)
LM_pred = LM.predict(X_test)
print("MSE(Linear Model): ",mean_squared_error(y_test, LM_pred))

sc = StandardScaler()
X_test_std = sc.fit_transform(X_test)
X_train_std = sc.fit_transform(X_train)
SV= SVR(kernel='rbf')
SV.fit(X_train_std, y_train)
SV_pred = SV.predict(X_test_std)
print("MSE(SVR): ",mean_squared_error(y_test, SV_pred))

DR = DecisionTreeRegressor(max_depth=3)
DR.fit(X_train, y_train)
DR_pred = DR.predict(X_test)
print("MSE(Decision Tree Regressor): ",mean_squared_error(y_test, DR_pred))

mix_pred = np.vstack((LM_pred, SV_pred, DR_pred))
mix_pred.shape

mean_pred = LM_pred*0.5+SV_pred*0.1+DR_pred*0.4
print("MSE(mean): ",mean_squared_error(y_test, mean_pred))

MSE(Linear Model):  2690647926.377604
MSE(SVR):  7119069689.683064
MSE(Decision Tree Regressor):  2553443455.30812
MSE(mean):  2470929971.541012


In [ ]:
from sklearn.linear_model import Lasso
Las= Lasso(alpha=0.1)
Las.fit(X_train, y_train)
Las_pred = Las.predict(X_test)
print("MSE(Lasso): ",mean_squared_error(y_test, Las_pred))

sc = StandardScaler()
X_test_std = sc.fit_transform(X_test)
X_train_std = sc.fit_transform(X_train)
SV= SVR(kernel='rbf',C=0.5)
SV.fit(X_train_std, y_train)
SV_pred = SV.predict(X_test_std)
print("MSE(SVR): ",mean_squared_error(y_test, SV_pred))

DR = DecisionTreeRegressor(max_depth=3)
DR.fit(X_train, y_train)
DR_pred = DR.predict(X_test)
print("MSE(Decision Tree Regressor): ",mean_squared_error(y_test, DR_pred))

mix_pred = np.vstack((LM_pred, SV_pred, DR_pred))
mix_pred.shape

mean_pred = Las_pred*0.5+SV_pred*0.05+DR_pred*0.45
print("MSE(mean): ",mean_squared_error(y_test, mean_pred))

MSE(Lasso):  2690647942.4335794
MSE(SVR):  7128920068.0851145
MSE(Decision Tree Regressor):  2553443455.30812
MSE(mean):  2413207951.9277987


In [ ]:
from sklearn.linear_model import Ridge
Rid= Ridge(alpha=0.1)
Rid.fit(X_train, y_train)
Rid_pred = Rid.predict(X_test)
print("MSE(Ridge): ",mean_squared_error(y_test, Rid_pred))

sc = StandardScaler()
X_test_std = sc.fit_transform(X_test)
X_train_std = sc.fit_transform(X_train)
SV= SVR(kernel='linear', C=100)
SV.fit(X_train_std, y_train)
SV_pred = SV.predict(X_test_std)
print("MSE(SVR): ",mean_squared_error(y_test, SV_pred))

DR = DecisionTreeRegressor(max_depth=9)
DR.fit(X_train, y_train)
DR_pred = DR.predict(X_test)
print("MSE(Decision Tree Regressor): ",mean_squared_error(y_test, DR_pred))

mix_pred = np.vstack((LM_pred, SV_pred, DR_pred))
mix_pred.shape

mean_pred = Rid_pred*0.2+SV_pred*0.1+DR_pred*0.7
print("MSE(mean): ",mean_squared_error(y_test, mean_pred))

MSE(Ridge):  2690647942.0877924
MSE(SVR):  3389628361.3601527
MSE(Decision Tree Regressor):  1766955102.332798
MSE(mean):  1695266986.4273043


## Problem 2

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
import lightgbm as lgb
import xgboost as xgb

np.random.seed(1)
rand_index = np.random.choice(X_train.index,1022, replace=True)
np.random.seed(1)
rand_index = np.random.choice(X_train.index,X_train.shape[0], replace=True)
X_train1 = X_train.loc[rand_index]
y_train1 = y_train.loc[rand_index]

np.random.seed(2)
rand_index = np.random.choice(X_train.index,X_train.shape[0], replace=True)
X_train2 = X_train.loc[rand_index]
y_train2 = y_train.loc[rand_index]

np.random.seed(3)
rand_index = np.random.choice(X_train.index,X_train.shape[0], replace=True).tolist()
X_train3 = X_train.loc[rand_index]
y_train3 = y_train.loc[rand_index]

In [ ]:
reg1 = GradientBoostingRegressor(n_estimators=100,max_depth=5).fit(X_train1, y_train1)
y_pred1 =reg1.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred1))
reg2 = GradientBoostingRegressor(n_estimators=500,max_depth=3).fit(X_train2, y_train2)
y_pred2 =reg2.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred2))
reg3 = GradientBoostingRegressor(n_estimators=250,max_depth=5).fit(X_train3, y_train3)
y_pred3 =reg3.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred3))
y_pred_mean = (y_pred1 + y_pred2 + y_pred3)/3
print("MSE(mean): ",mean_squared_error(y_test, y_pred_mean))

MSE:  1955856381.8803396
MSE:  2246120995.481195
MSE:  1725817235.2522635
MSE(mean):  1659935727.6287725


In [ ]:
reg1 = xgb.XGBRegressor(n_estimators=100,max_depth=5).fit(X_train1, y_train1)
y_pred1 =reg1.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred1))
reg2 = xgb.XGBRegressor(n_estimators=500,max_depth=3).fit(X_train2, y_train2)
y_pred2 =reg2.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred2))
reg3 = xgb.XGBRegressor(n_estimators=250,max_depth=5).fit(X_train3, y_train3)
y_pred3 =reg3.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred3))
y_pred_mean = (y_pred1 + y_pred2 + y_pred3)/3
print("MSE(mean): ",mean_squared_error(y_test, y_pred_mean))

MSE:  2302274400.565713
MSE:  2468960358.254284
MSE:  1958559489.3734016
MSE(mean):  1811190326.9155846


In [ ]:
reg1 = lgb.LGBMRegressor(n_estimators=100,max_depth=5).fit(X_train1, y_train1)
y_pred1 =reg1.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred1))
reg2 = lgb.LGBMRegressor(n_estimators=500,max_depth=3).fit(X_train2, y_train2)
y_pred2 =reg2.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred2))
reg3 = lgb.LGBMRegressor(n_estimators=250,max_depth=5).fit(X_train3, y_train3)
y_pred3 =reg3.predict(X_test)
print("MSE: ",mean_squared_error(y_test, y_pred3))
y_pred_mean = (y_pred1 + y_pred2 + y_pred3)/3
print("MSE(mean): ",mean_squared_error(y_test, y_pred_mean))
y_pred3[1]

MSE:  1996989149.286145
MSE:  2217785612.142733
MSE:  2337926346.668943
MSE(mean):  2010251814.6958816


149261.18481853406

- Scratch Implementation for Bagging

In [ ]:
class Bagging():
     
    def fit(self, models, X, y):
        self.model_list = []
        for j, model in enumerate(models):
            np.random.seed(j)
            self.rand_index = np.random.choice(X.index,X.shape[0], replace=True)
            self.X_rand = X.loc[self.rand_index]
            self.y_rand = y.loc[self.rand_index]
            self.model_list.append(model.fit(self.X_rand, self.y_rand))
            
    def predict(self, X, y):
        print(X.shape[0])
        print(len(self.model_list))
        self.pred_data = np.zeros((X.shape[0],len(self.model_list)))
        for i, model in enumerate(self.model_list):
            self.pred = model.predict(X)
            self.pred_data[:,i] = self.pred
        self.final_pred = np.mean(self.pred_data, axis=1)
        print("MSE(mean): ",mean_squared_error(y, self.final_pred))
        return self.final_pred

In [ ]:
models = [xgb.XGBRegressor(n_estimators=100,max_depth=5), GradientBoostingRegressor(n_estimators=100,max_depth=5), lgb.LGBMRegressor(n_estimators=100,max_depth=5)]
bg = Bagging()
bg.fit(models=models, X = X_train, y = y_train)
bg.predict(X_test, y_test)[:10]

438
3
MSE(mean):  1843004525.0391715


array([233606.53154969, 156557.12682114, 128544.76905402, 162812.42505345,
       119902.95170025,  93717.61151535, 202045.47302486, 123859.74040471,
       565346.0913109 , 148427.40559746])

In [ ]:
models = [lgb.LGBMRegressor(n_estimators=100,max_depth=5), lgb.LGBMRegressor(n_estimators=100,max_depth=5), lgb.LGBMRegressor(n_estimators=100,max_depth=5)]
bg = Bagging()
bg.fit(models=models, X = X_train, y = y_train)
bg.predict(X_test, y_test)[:10]

438
3
MSE(mean):  1905905323.963103


array([186616.01381421, 154654.02881744, 128076.41901312, 184057.70727728,
       128618.50371924,  91991.24366953, 202164.25872405, 126932.11921891,
       441678.27135167, 146946.96392326])

In [ ]:
models = [xgb.XGBRegressor(n_estimators=100,max_depth=5), xgb.XGBRegressor(n_estimators=100,max_depth=5), xgb.XGBRegressor(n_estimators=100,max_depth=5)]
bg = Bagging()
bg.fit(models=models, X = X_train, y = y_train)
bg.predict(X_test, y_test)[:10]

438
3
MSE(mean):  1881306593.3967283


array([254122.953125  , 149782.68229167, 126505.11197917, 151397.40625   ,
       119442.3671875 ,  93480.6328125 , 199798.34375   , 121269.84635417,
       585070.83333333, 147071.07291667])

In [ ]:
models = [xgb.XGBRegressor(n_estimators=100,max_depth=5), lgb.LGBMRegressor(n_estimators=100,max_depth=5), GradientBoostingRegressor(n_estimators=100,max_depth=5)]
bg = Bagging()
bg.fit(models=models, X = X_train, y = y_train)
bg.predict(X_test, y_test)[:10]

438
3
MSE(mean):  1829244462.2411044


array([243222.01388204, 159581.7916357 , 127472.41755668, 164737.29674377,
       122297.37556448,  93004.30507923, 208187.83383771, 121070.61922549,
       481494.92776656, 152658.97154074])

## Problem 3

In [ ]:
X1_train, X2_train, X3_train  = np.split(X_train, [340, 681])
y1_train, y2_train, y3_train  = np.split(y_train, [340, 681])
X_train1 = np.vstack((X2_train, X3_train))
y_train1 = np.hstack((y2_train, y3_train))
reg1_Gr = GradientBoostingRegressor(n_estimators=100,max_depth=5).fit(X_train1, y_train1)
y_pred1_reg1_Gr =reg1_Gr.predict(X1_train)
print("MSE_1: ",mean_squared_error(y1_train, y_pred1_reg1_Gr))
X_train2 = np.vstack((X1_train, X3_train))
y_train2 = np.hstack((y1_train, y3_train))
reg2_Gr = GradientBoostingRegressor(n_estimators=500,max_depth=3).fit(X_train2, y_train2)
y_pred2_reg2_Gr =reg2_Gr.predict(X2_train)
print("MSE_2: ",mean_squared_error(y2_train, y_pred2_reg2_Gr))
X_train3 = np.vstack((X1_train, X2_train))
y_train3 = np.hstack((y1_train, y2_train))
reg3_Gr = GradientBoostingRegressor(n_estimators=250,max_depth=5).fit(X_train3, y_train3)
y_pred3_reg3_Gr =reg3_Gr.predict(X3_train)
print("MSE_2: ",mean_squared_error(y3_train, y_pred3_reg3_Gr))
y_train_Gr = np.hstack((y_pred1_reg1_Gr, y_pred2_reg2_Gr, y_pred2_reg2_Gr))

MSE_1:  2071427144.2454295
MSE_2:  2302950146.6236258
MSE_2:  1447210511.942195


In [ ]:
X_train1 = np.vstack((X2_train, X3_train))
y_train1 = np.hstack((y2_train, y3_train))
reg1_LG = lgb.LGBMRegressor(n_estimators=100,max_depth=5).fit(X_train1, y_train1)
y_pred1_reg1_LG =reg1_LG.predict(X1_train)
print("MSE_1: ",mean_squared_error(y1_train, y_pred1_reg1_LG))
X_train2 = np.vstack((X1_train, X3_train))
y_train2 = np.hstack((y1_train, y3_train))
reg2_LG = lgb.LGBMRegressor(n_estimators=500,max_depth=3).fit(X_train2, y_train2)
y_pred2_reg2_LG =reg2_LG.predict(X2_train)
print("MSE_2: ",mean_squared_error(y2_train, y_pred2_reg2_LG))
X_train3 = np.vstack((X1_train, X2_train))
y_train3 = np.hstack((y1_train, y2_train))
reg3_LG = lgb.LGBMRegressor(n_estimators=250,max_depth=5).fit(X_train3, y_train3)
y_pred3_reg3_LG =reg3_LG.predict(X3_train)
print("MSE_3: ",mean_squared_error(y3_train, y_pred3_reg3_LG))
y_train_LG = np.hstack((y_pred1_reg1_LG, y_pred2_reg2_LG, y_pred2_reg2_LG))

MSE_1:  1789291655.0779407
MSE_2:  2088962682.1700788
MSE_3:  1383718320.4924493


In [ ]:
X_train1 = np.vstack((X2_train, X3_train))
y_train1 = np.hstack((y2_train, y3_train))
reg1_RF = RandomForestRegressor(n_estimators=100,max_depth=5).fit(X_train1, y_train1)
y_pred1_reg1_RF =reg1_RF.predict(X1_train)
print("MSE_1: ",mean_squared_error(y1_train, y_pred1_reg1_RF))
X_train2 = np.vstack((X1_train, X3_train))
y_train2 = np.hstack((y1_train, y3_train))
reg2_RF = RandomForestRegressor(n_estimators=500,max_depth=3).fit(X_train2, y_train2)
y_pred2_reg2_RF =reg2_RF.predict(X2_train)
print("MSE_2: ",mean_squared_error(y2_train, y_pred2_reg2_RF))
X_train3 = np.vstack((X1_train, X2_train))
y_train3 = np.hstack((y1_train, y2_train))
reg3_RF = RandomForestRegressor(n_estimators=250,max_depth=5).fit(X_train3, y_train3)
y_pred3_reg3_RF =reg3_RF.predict(X3_train)
print("MSE_3)",mean_squared_error(y3_train, y_pred3_reg3_RF))
y_train_RF = np.hstack((y_pred1_reg1_RF, y_pred2_reg2_RF, y_pred2_reg2_RF))

MSE_1:  1886284941.1994443
MSE_2:  2422957242.6368184
MSE_3) 1181644534.6643596


In [ ]:
train_mix = np.vstack((y_train_Gr, y_train_LG, y_train_RF)).T

xgb.XGBRegressor
reg_end = xgb.XGBRegressor(n_estimators=250,max_depth=5).fit(train_mix, y_train)

X_test1_Gr =reg1_Gr.predict(X_test)
X_test2_Gr =reg2_Gr.predict(X_test)
X_test3_Gr = reg3_Gr.predict(X_test)
y_test_Gr = (X_test1_Gr + X_test2_Gr + X_test3_Gr) /3

X_test1_LG =reg1_LG.predict(X_test)
X_test2_LG =reg2_LG.predict(X_test)
X_test3_LG = reg3_LG.predict(X_test)
y_test_LG = (X_test1_LG + X_test2_LG + X_test3_LG) /3

X_test1_RF =reg1_RF.predict(X_test)
X_test2_RF =reg2_RF.predict(X_test)
X_test3_RF = reg3_RF.predict(X_test)
y_test_RF = (X_test1_RF + X_test2_RF + X_test3_RF) /3

In [ ]:
X_test_end = np.vstack((y_test_Gr,y_test_LG,y_test_RF)).T
y_pred_end = reg_end.predict(X_test_end)

In [ ]:
print("MSE(Stacking): ",mean_squared_error(y_test, y_pred_end))

MSE(Stacking):  3451768164.651193


In [ ]:
from sklearn.model_selection import KFold

class Stacking():
    
    def __init__(self,models,end_model):
        self.models = models
        self.end_model = end_model

    def fit(self,X,y,K,seed):
        self.K = K
        KF = KFold(n_splits=K, random_state=seed, shuffle=True)
        self.pred_data = np.array([])
        X = np.array(X)
        y = np.array(y)
        self.preds = np.array([])
        self.model_list = []
        for i, model in enumerate(self.models):
            for train_index, test_index in KF.split(X):
                self.model_list.append(model.fit(X[train_index],y[train_index]))
                y_pred = model.predict(X[test_index])
                self.preds = np.append(self.preds, y_pred)
        self.preds = self.preds.reshape(len(self.models),X.shape[0]).T
        self.end_model.fit(self.preds, y)
       
    def predict(self,X, y):
        X = np.array(X)
        y = np.array(y)
        self.test_array = np.array([])
        self.final_test = np.zeros((X.shape[0],self.K))
        for model in self.model_list:
            y_pred_test = model.predict(X)
            self.test_array = np.append(self.test_array, y_pred_test)
        self.test_array=self.test_array.reshape(len(self.models)*self.K, X.shape[0]).T
        print("Test-->", self.test_array.shape)
        for j, i in enumerate(range(0,len(self.models)*self.K-self.K, self.K)):
            self.mean_pred = np.mean(self.test_array[:,i:i+self.K], axis=1)
            self.final_test[:,j] = self.mean_pred
        self.final_pred = self.end_model.predict(self.final_test)
        print("Last stage-->", self.final_test.shape)
        return self.final_pred

In [ ]:
models = [xgb.XGBRegressor(n_estimators=100,max_depth=5), GradientBoostingRegressor(n_estimators=100,max_depth=5), lgb.LGBMRegressor(n_estimators=100,max_depth=5)]
St = Stacking(models,end_model=GradientBoostingRegressor(n_estimators=100,max_depth=5))
St.fit(X=X_train, y=y_train,K=3,seed=0)
y_pred_end = St.predict(X_test, y_test)
print("MSE(Stacking): ",mean_squared_error(y_test, y_pred_end))

Test--> (438, 9)
Last stage--> (438, 3)
MSE(Stacking):  9479604217.809435
